### ISSUE TITLE
Anti-CV filter list on Facebook creates a display issue on the main feed

### ISSUE THREAD

**Issue by adblocksupport** [abp-filters/abp-filters-anti-cv#1357] opened 2023-05-08 14:43 UTC
### List the website(s) where you encounter issues with ABP filters 

* Facebook

### Define the problem 

With the Anti-Circumvention filter list enabled, the Facebook timeline is glitching and does not display correctly

### List all of your filter lists 

* AC
* EasyList

### Tell us about your system configuration 

- Browser and version: Chrome Version 112.0.5615.137 (Official Build) (x86_64)
- AdBlock version: 5.6

### Other details 

Disabling the AC filter list resolves the issue

**Comment by delta9A** [comment] 2023-05-08 16:43
@adblocksupport we apologies for the inconvenience caused. 

May I ask you please to update your filter list and check whether issue persists or not? 

If possible may I also ask you please to provide the location/language you are using on Facebook? so we can try to reproduce the issue on our end.

Thank you so much.

**Comment by delta9A** [comment] 2023-05-11 08:54
@adblocksupport may I ask you please to confirm whether issue persists or not? 
Thank you.

**Comment by delta9A** [comment] 2023-05-12 10:30
@adblocksupport I'm closing this issue since we did not get any answers from you. 
Feel free to reply here or open a new one in case you are still facing the issue. 
Thank you.

**Closed by delta9A** 2023-05-12 10:30 UTC
