### ISSUE TITLE
AdBlock Plus and AdBlock break the page if it has freeze-element filter enabled

### ISSUE THREAD

**Issue by MeFoDy** [abp-filters/abp-filters-anti-cv#541] opened 2021-01-20 20:11 UTC
### List the website(s) where you encounter issues with ABP filters 

* `https://www.newser.com/`
* `https://yandex.ru/search/?text=%D0%B3%D0%B5%D1%80%D0%B1%20%D0%B3%D0%BE%D1%80%D0%BE%D0%B4%20%D1%87%D0%B0%D1%81%D0%BE%D0%B2%20%D1%8F%D1%80%20%D0%B4%D0%BE%D0%BD%D0%B5%D1%86%D0%BA%D0%B0%D1%8F%20%D0%BE%D0%B1%D0%BB%D0%B0%D1%81%D1%82%D1%8C&rdrnd=118176&lr=213&redircnt=1611172521.1`
* `https://yandex.ru/`

https://reports.adblockplus.org/98bdfbd5-3213-4102-a132-07558632732c

### Define the problem 

When I enable both AdBlock Plus and AdBlock with ABP filters enabled (from this url: https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt) the site is broken. JS in not working and the footer is not visible.
I found that it is connected with the `freeze-element` filter. If I use only my custom filter like `yandex.ru#$#freeze-element .not-exists` for both of AB and ABP, I have next errors:
```
Uncaught TypeError: b.appendChild is not a function
    at jquery.min.js:3
    at jquery.min.js:3
    at jquery.min.js:2
    at jquery.min.js:2
(anonymous) @ jquery.min.js:3
(anonymous) @ jquery.min.js:3
(anonymous) @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
PUfDfN7ncT7Fx4zB18MAlohbXh0.js:3 Uncaught ReferenceError: jQuery is not defined
    at PUfDfN7ncT7Fx4zB18MAlohbXh0.js:3
```

### Screenshot(s) 
![broken-yandex](https://user-images.githubusercontent.com/1439919/105228668-e833af00-5b73-11eb-9d18-f81f1ea4e057.png)

It should have the footer and working JS as well.

### List all of your filter lists 

Only custom filter.
```
yandex.ru#$#freeze-element .not-exists
```

### Tell us about your system configuration 

- Operating system and version: macOS 10.15.7
- Browser and version: Chrome 88.0.4324.96
- Adblock Plus version: 3.10.1

### Other details 

I found similar problem in issues about `bing.com`: https://github.com/abp-filters/abp-filters-anti-cv/issues/465#issuecomment-701530605

**Comment by MeFoDy** [comment] 2021-01-20 20:12
It looks like my problem is connected with https://github.com/abp-filters/abp-filters-anti-cv/commit/e8d95bff178c4856c472bbe4d67b387f3541aa61

**Comment by dimisa-RUAdList** [comment] 2021-01-20 23:08
Using two or more blockers at the same time breaks a lot of resources. Don't use this configuration.

**Comment by evgeny-vetrov** [comment] 2021-01-21 10:47
> Using two or more blockers at the same time breaks a lot of resources. Don't use this configuration.

I have the same issue with Chrome 88 and only "Adblock" extension, it's looks like not a problem of conflict of two extensions.

**Comment by wizmak** [comment] 2021-01-21 11:16
@MeFoDy Thank you for reporting!
We're aware of this issue, it's already fixed in ABP, and a similar fix should land soon in AdBlock, then this issue should be fixed.
But in general, as @dimisa-RUAdList mentioned, it's not recommended to use more than one ad blocker simultaneously.

**Comment by wizmak** [comment] 2021-01-21 11:18
@evgeny-vetrov  
> I have the same issue with Chrome 88 and only "Adblock" extension, it's looks like not a problem of conflict of two extensions.

It seems to be working fine on Chrome 88 + AdBlock 4.27.0 only. Can you double-check if this is indeed the case?

**Comment by evgeny-vetrov** [comment] 2021-01-21 12:38
> @evgeny-vetrov
> 
> > I have the same issue with Chrome 88 and only "Adblock" extension, it's looks like not a problem of conflict of two extensions.
> 
> It seems to be working fine on Chrome 88 + AdBlock 4.27.0 only. Can you double-check if this is indeed the case?

can't reproduce now, only when both adblock plus and adblock are installed

**Comment by evgeny-vetrov** [comment] 2021-01-21 13:05
@wizmak @arsykan are u considering to rollback e8d95bf since Adblock+ABP turned out to be a popular setup and a lot of users are suffering after release of this commit?

**Comment by arsykan** [comment] 2021-01-21 17:13
@evgeny-vetrov  @MeFoDy  Thanks for reporting! yes we considered removing the filter & it was removed
https://github.com/abp-filters/abp-filters-anti-cv/commit/0e934c9cf67390bb5dd683f743c6cc418129f4f9

**Closed** 2021-01-22 12:28 UTC

**Comment by RepubliqueMedia** [comment] 2021-03-01 07:50
Same on newser.com

**Comment by arsykan** [comment] 2021-03-01 11:50
@RepubliqueMedia 
for me it is an adblocker message, is that the case here? or some functionality is broken?

**Comment by RepubliqueMedia** [comment] 2021-03-01 12:21
Can't connect to my account or manage my newsletter settings.
