### ISSUE TITLE
ABP is breaking Ranker.com images

### ISSUE THREAD

**Issue by abrob1224** [abp-filters/abp-filters-anti-cv#26] opened 2018-12-07 20:43 UTC
### List the website(s) where you encounter issues with ABP filters 

* Ranker.com

### Define the problem 

I'm browsing the site and seeing broken images.

### List all of your filter lists

Disabled - Adblock Warning Removal List
Active ABP filters
Active Easylist
Active Allow non-intrusive advertising

### Tell us about your system configuration 

- Operating system and version: MacBook Pro / Mojave, 10.14.1
- Browser and version: Chrome Version 70.0.3538.110 (Official Build) (64-bit)
- Adblock Plus version: 3.4.2, Allow Acceptable Ads checked

### Other details 

<img width="999" alt="screen shot 2018-12-07 at 12 42 51 pm" src="https://user-images.githubusercontent.com/45699092/49671760-bad02980-fa1d-11e8-8510-94d73dc78a36.png">

**Comment by smed79** [comment] 2018-12-08 01:53
Images loads fine here https://i.imgur.com/29hJOM2.png

submit an Adblock Plus issue report https://adblockplus.org/getting_started#false-positives

**Comment by monzta** [comment] 2018-12-10 09:54
I'm also unable to reproduce this issue. Closing.

**Closed by monzta** 2018-12-10 09:54 UTC
