### ISSUE TITLE
Remove ebay promoted infotip

### ISSUE THREAD

**Issue by MaiDeveloper** [abp-filters/abp-filters-anti-cv#1411] opened 2023-08-14 21:11 UTC
### List the website(s) where you encounter issues with ABP filters
eBay

### Define the problem
Promoted store is hidden

Please remove the following rule in #CV-691
```
ebay.com,ebay.com.au,ebay.co.uk,ebay.com.my,ebay.ie,ebay.ca,ebay.at,ebay.de,ebay.ch,ebay.pl,ebay.it,ebay.nl,ebay.be,ebay.fr,ebay.es,ebay.com.hk,ebay.com.sg,ebay.ph#$#hide-if-matches-xpath './/div[contains(@class,"sponsored-infotip")]/parent::div[starts-with(@class,"ads")]/parent::div[contains(@class,"ads")]/ancestor::div[@id and @aria-label="Advertisement"]'
```

URL: https://www.ebay.com/itm/275353759236
<img width="1640" alt="Screenshot 2023-08-15 at 11 01 35 AM" src="https://github.com/abp-filters/abp-filters-anti-cv/assets/48327829/a6c6dd6d-9dd9-4cce-a62d-b482cc31be9e">
<img width="1670" alt="Screenshot 2023-08-15 at 10 54 48 AM" src="https://github.com/abp-filters/abp-filters-anti-cv/assets/48327829/e51013e6-d778-4551-90c1-a42e8898d7cd">

The bottom right promoted store is hidden.
<img width="318" alt="Screenshot 2023-08-15 at 11 03 07 AM" src="https://github.com/abp-filters/abp-filters-anti-cv/assets/48327829/5ecf22b3-5f36-4dd1-bdab-aa250025bfca">

**Comment by delta9A** [comment] 2023-08-15 07:44
Hi @MaiDeveloper 

Thanks for your report.

Could you please share an URL and screenshot so we can try to reproduce this issue?

**Comment by MaiDeveloper** [comment] 2023-08-15 15:04
Hi @delta9A,

I have posted the screenshots and URL. Please take a look.

**Comment by delta9A** [comment] 2023-08-15 15:25
@MaiDeveloper thanks for adding URL and screenshots to the issue description.

The promoted store banner you shared: [Shop related items](https://www.ebay.com/str/bissellhomecareinc?_sacat=20614&promoted_items=325264571123,324304714563,324303721109&amdata=encpd%3AAQAIAAABgFd3i%2FguAfOVPDxHHiLF8oR9z9%2BVhL0XkyARRklSxPanAIvD2NveFcP0QKrMR9k%2BDupqrHeSstl88beCqs2Uxjj5wnJyTQaAKCpd5xMZLtFVtwo2W8ZZMUstmRlhz4EP%2B6fXWZ1CoHx7jJxA0InB34dxmM4Wa6uEq0zvT7Bu0sHFgF4oKnSVovtRdYsKZi%2B6i66GP0ch2mTy7GgIEaoCj6u5Z0WGmnglAKJ%2ByHMG1xeqQGPfd3oI2%2Bhl5Mu%2BZpHgZV7CBCw9BPtULxWnXNtfyZ1%2FYu3ZvrX60%2Fskrhfav34nBubIG87%2FJNqNKOrdTfYsUVjphMnvjs3kK4V%2Fw4GyuVDt4nGbtREBIEukuFtEurSo7he%2F3nvt3%2BLdyD9sp6BYBYAJxPi8kEDm0RekcfMRjS01pLETgll88EG9ZLlVBtHyfhkmsXiiJLjAuJ5xF%2FR83DhoPAPDEwVDzSrQB3AHkloALOCwqUPd1nLN%2BiyesZzYw5uMz4KFKwjgOc9pSKBLUg%3D%3D) is considered an ad, so that's why it's hidden in our list.

**Comment by delta9A** [comment] 2023-08-15 15:32
I'm closing this issue since filter is hiding an ad and not causing any False Positives.

**Closed by delta9A** 2023-08-15 15:32 UTC

**Comment by bill-min** [comment] 2023-08-18 20:15
Hi @delta9A , I am just curious about the definition of ads here, and the whole purpose of AdsBlocker is to enhance user experience. The promoted store section is designed specific for that location with bunch of designing iterations which I believe is not "intrusive" at all to user experience. It is a truly a merchandise recommendation based on what user is currently visiting. It has no difference from the merch carousel underneath. If you don't mind could you clarify the goal here?

**Comment by delta9A** [comment] 2023-08-21 10:55
> Hi @delta9A , I am just curious about the definition of ads here, and the whole purpose of AdsBlocker is to enhance user experience. The promoted store section is designed specific for that location with bunch of designing iterations which I believe is not "intrusive" at all to user experience. It is a truly a merchandise recommendation based on what user is currently visiting. It has no difference from the merch carousel underneath. If you don't mind could you clarify the goal here?

Hi @bill-min thanks for your question. We understand your concerns and  we are working on it. 
We will get back to you as soon as we can with further clarifications.

**Comment by delta9A** [comment] 2023-08-22 12:51
> > Hi @delta9A , I am just curious about the definition of ads here, and the whole purpose of AdsBlocker is to enhance user experience. The promoted store section is designed specific for that location with bunch of designing iterations which I believe is not "intrusive" at all to user experience. It is a truly a merchandise recommendation based on what user is currently visiting. It has no difference from the merch carousel underneath. If you don't mind could you clarify the goal here?
> 
> Hi @bill-min thanks for your question. We understand your concerns and we are working on it. We will get back to you as soon as we can with further clarifications.

Hi @bill-min thanks for your patience. In response to your question above, the specifications of ad formats and sizes are determined by over a decade of user research and feedback. I am not sure if you are aware but the majority of Adblockers are part of the [Acceptable Ads](acceptableads.com) ecosystem. The large majority of tech companies (Amazon, Google and Microsoft) already work with [Acceptable Ads](acceptableads.com) rather than using circumvention. With some small tweaks I am pretty sure eBay's ads could be considered under these criteria. If you like I could setup a discussion with someone on our team to find a more long term sustainable solution.
