### ISSUE TITLE
Quora: Ad blocker hides the upvote button in feed

### ISSUE THREAD

**Issue by gleeq** [abp-filters/abp-filters-anti-cv#73] opened 2019-03-04 18:58 UTC
### List the website(s) where you encounter issues with ABP filters 

quora.com
https://www.quora.com/topic/World-War-II

### Define the problem 

1. It seems the blocking ad is not clean, it still leaves an empty box. (which is ok i guess?)
2. When expanding an answer, abp is able to block the ad, but it also blocks the upvote button. I can go to the answer and workaround this but sort of inconvenient. 

### Screenshot(s) 

https://cl.ly/90e404456df3

### Tell us about your system configuration 

- Operating system and version: Mac
- Browser and version: latest
- Adblock Plus version: latest

### Other details 

Original thread:
https://github.com/abp-filters/abp-filters-anti-cv/issues/53

Thanks!!

**Comment by wizmak** [comment] 2019-03-05 09:15
@gleeq thanks for your report, good catch.

1. Empty boxes are ok for now.
2. Couldn't reproduce, but I see the issue, and I just pushed a fix for it. Can you check again in few mins, and let me know if the issue persists?

**Comment by gleeq** [comment] 2019-03-05 20:29
i think the first one (blank blcok) still exist? see: https://cl.ly/e10a04cde1af i updated my filter to the latest, and can see if I disable the filter, the ad show up.

**Comment by wizmak** [comment] 2019-03-05 20:48
> i think the first one (blank blcok) still exist? see: https://cl.ly/e10a04cde1af i updated my filter to the latest, and can see if I disable the filter, the ad show up.

Yes, it does, I didn't push a fix for this. How about the other issue? does it happen still?

**Comment by gleeq** [comment] 2019-03-06 01:32
yeah i think the upvote is back! thank you! https://cl.ly/49861b02661a

**Comment by wizmak** [comment] 2019-03-06 07:21
welcome! Closing this issue then.

**Closed by wizmak** 2019-03-06 07:21 UTC
